// Generated by https://quicktype.io

export interface DashboardSummaryResponse {
    numberOfOrders: number;
    paidOrders: number;
    numberOfClients: number;
    numberOfProducts: number;
    productsWithNoIventory: number;
    lowInvetory: number;
    notPaidOrders: number;
}
